Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: true
  # Change the default 80 chars limit value
  Max: 120

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 5

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 150

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
